spring:
  datasource:
    url : jdbc:mysql://localhost:3306/bootDemo?user=root&password=root&useUnicode=true&characterEncoding=UTF8
    username : root
    password : abcd123!
    driverClassName : com.mysql.jdbc.Driver
  jpa:
    database : MYSQL
    show-sql : true
    hibernate:
      ddl-auto : update
#      naming-strategy : org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect : org.hibernate.dialect.MySQL5Dialect